updates...

diff --git a/devsync b/devsync
--- a/devsync
+++ b/devsync
@@ -3,26 +3,87 @@ OPTERR=0
 BRANCH=`git rev-parse --abbrev-ref HEAD`
 function help {
 	echo <<EOF "
-
-USAGE: devsync [opt]... [optarg]...
+USAGE: go [opt]... [optarg]...
 Automatically synchronize local development branch with a remote dev server.
-
-  -o 				Set new origin branch
-  -n  [name]		Create new branch, and set its upstream target
+  -o 			Set new origin branch
+  -n  [name]	Create new branch, and set its upstream target
+  -m 			Supply a custom message for the commit
+  -r			Create a pull request in github for your current local branch
+  -d			Delete your current local branch
 "
 EOF
 }
-
-while getopts hn:o opt; do
+function getBranch {
+	echo `git rev-parse --abbrev-ref HEAD`
+}
+function escapeBranch {
+	echo `echo $BRANCH | sed -e 's/_/N/g'`
+}
+# returns the number of local branches
+function getNumBranches {
+	echo `git rev-parse --abbrev-ref --branches | grep -P '^((?!dev)(?!master).)' | wc -l`
+}
+function isLocal {
+	if [ `git rev-parse --abbrev-ref HEAD | grep -P '^((?!dev)(?!master).)'` ]; then echo 1; fi
+}
+# If we're on a local branch, return the current branch.  Else, return the first local branch with no pullRequest pending (if none, return the first local branch)
+function getLocal {
+	if [ `isLocal` ]; then
+		echo `git rev-parse --abbrev-ref HEAD`
+	else
+		RET=""
+		for ((i=1; i<=`getNumBranches`; i++)); do
+			CURR_BRANCH=`git rev-parse --abbrev-ref --branches | grep -P '^((?!dev)(?!master).)' | sed "$i q;d"`
+			if [ "`git config --local --bool $(echo $CURR_BRANCH | sed -e 's/_/N/g').hasPullRequest`" = false ]; then
+				RET=$CURR_BRANCH
+				break
+			fi
+		done
+		if [ RET = "" ]; then RET=`git rev-parse --abbrev-ref --branches | grep -P '^((?!dev)(?!master).)' | head -n 1`; fi
+		echo $RET
+	fi
+}
+function localExists {
+	if [ `getLocal` ]; then echo 1; fi
+}
+function getCommitNum {
+	if [ `localExists` ]; then echo `git config --local $(getLocal | sed -e 's/_/N/g').commitNum`; fi
+}
+# Make sure we're on a local branch.  Exit if there is no local branch.
+function switchToLocal {
+	if [ `localExists` ]; then
+		LOCAL=`getLocal`
+		if [ $BRANCH != $LOCAL ]; then
+			git checkout $LOCAL
+			BRANCH=$LOCAL
+		fi
+	else
+		echo "You don't have a local feature branch.  Create one with 'go -n [name]'"
+		exit 1;
+	fi
+}
+function commitChanges {
+	echo "Adding, committing, merging into dev, pushing dev, checking out '$BRANCH' again"
+	git add --all && git commit -m "$MESSAGE" && git push && git checkout dev && git merge $BRANCH && git push && git checkout $BRANCH
+	git config --local `escapeBranch`.commitNum $((`git config --local $(escapeBranch).commitNum` + 1))
+}
+MESSAGE="`getLocal` #`getCommitNum`"
+while getopts thn:om:rd opt; do
 	case $opt in
+		t)
+			echo "Creating pull request for branch '`getLocal`'"
+			#if [ `getLocal` ]; then echo "Local branch exists!"; else echo "No local branch..."; fi
+			exit 0
+			;;
 		h)
 			help
 			exit 0
 			;;
 		o)
+			switchToLocal
 			echo "Setting upstream path 'origin/$BRANCH'"
 			{
-				git branch --set-upstream-to $BRANCH origin/$BRANCH 
+				git branch --set-upstream-to origin/$BRANCH
 			} || {
 				echo "ERROR: Could not set upstream target." >&2
 			}
@@ -32,18 +93,55 @@ while getopts hn:o opt; do
 			BRANCH=$OPTARG
 			echo "Creating new branch '$BRANCH' with upstream target 'origin/$BRANCH'"
 			{
-				git checkout master 
+				git checkout master
+				git pull
 				git checkout -b $BRANCH 
 				git push origin $BRANCH 
-				git branch --set-upstream-to $BRANCH origin/$BRANCH 
+				git branch --set-upstream-to origin/$BRANCH 
+				git config --local `escapeBranch`.commitNum 1 && git config --local `escapeBranch`.hasPullRequest 0
 			} || {
 				echo "ERROR: Could not set upstream target." >&2
 				echo "Cleaning up..."
 				git checkout -- *
 				git checkout master
-				git branch -d $BRANCH
+				git branch -d $BRANCH && git push origin :$BRANCH
 				echo "Exiting"
 			}
+			exit 0
+			;;
+		m)
+			MESSAGE=$OPTARG
+			;;
+		r)
+			echo "Creating pull request for branch '`getLocal`'"
+			switchToLocal
+			{
+				REPO=`git remote show origin | grep 'Fetch URL' | cut -d'/' -f 5 | cut -d'.' -f 1`
+				DATA="{\"title\": \"$BRANCH\", \"head\": \"$BRANCH\", \"base\": \"master\", \"body\": \"Iz Kurtzavvin vun yiht?\"}"
+				curl -so "/var/log/github_pullrequest.log" -X POST -d "$DATA" -H "Authorization: token `git config --global user.token`" https://api.github.com/repos/ipartnr8/$REPO/pulls
+				git config --local `escapeBranch`.hasPullRequest 1
+				echo "Pull request created successfully"
+			} || {
+				echo "ERROR: api request failed." >&2
+				exit 1
+			}
+			
+			exit 0
+			;;
+		d)
+			switchToLocal
+			
+			if [ "`git status | grep 'nothing to commit'`" = "" ]; then
+				echo "Couldn't delete local branch.  You have uncommitted changes.  Committing them..."
+				commitChanges
+				echo "Recommended: Run 'go -r' to create a pull request for your latest changes."
+				echo "Otherwise, run 'go -d' again to delete"
+				exit 1
+			fi
+			
+			echo "Deleting your local branch"
+			git config --local --unset `escapeBranch`.commitNum && git config --local --unset `escapeBranch`.hasPullRequest
+			git checkout master && git branch -d $BRANCH && git push origin :$BRANCH
 			exit 0
 			;;
 		\?)
@@ -53,5 +151,10 @@ while getopts hn:o opt; do
 			;;
 	esac
 done
-
-git push && git checkout dev && git merge $BRANCH && git push && git checkout $BRANCH
+switchToLocal
+if [ "`git status | grep 'nothing to commit'`" = "" ]; then
+	commitChanges
+else
+	echo "Nothing to commit.  Exiting..."
+	exit 1;
+fi
